include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: false
    prefer_double_quotes: false
    public_member_api_docs: false
    avoid_classes_with_only_static_members: false
    avoid_setters_without_getters: false
    constant_identifier_names: false

    lines_longer_than_80_chars: false
    always_specify_types: true
    sort_constructors_first: true

# include: package:lint/analysis_options.yaml

# analyzer:
#   exclude:
#     - lib/api/**
#     - lib/carrom/**
#     - lib/common/**
#     - lib/fantasy/**
#     - lib/howzat/**
#     - lib/models/**
#     - lib/pages/**
#     - lib/resources/**
#     - lib/rummy/**
#     - lib/solitaire/**
#     - lib/utils/**
#     - lib/new/screens/**
#     - lib/new/tools/**
#     - lib/new/utils/**
#     - lib/new/widgets/**
#     - lib/new/repository/**
#     - lib/new/routes/route_handler.impl.dart
# linter:
#   rules:
#     # Make constructors the first thing in every class
#     sort_constructors_first: true

#     # The new tabs vs. spaces. Choose wisely
#     prefer_single_quotes: false
#     prefer_double_quotes: false

#     # Good packages document everything
#     public_member_api_docs: false

#     # Blindly follow the Flutter code style, which prefers types everywhere
#     always_specify_types: true

#     # Back to the 80s
#     lines_longer_than_80_chars: false

#     # Use parameter order as in json response
#     always_put_required_named_parameters_first: true

#     # Util classes are awesome!
#     avoid_classes_with_only_static_members: false

#     unnecessary_getters_setters: false

#     constant_identifier_names: false

#     avoid_function_literals_in_foreach_calls: false
